name: hedwig
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.16.0
  - certifi=2020.4.5.1
  - dbus=1.13.6
  - expat=2.2.9
  - ffmpeg=4.1.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - geos=3.8.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.58.3
  - gmp=6.2.0
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - icu=64.2
  - jasper=1.900.1
  - jpeg=9c
  - krb5=1.16.4
  - lame=3.100
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.4
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.8.3
  - ncurses=6.1
  - nettle=3.4.1
  - numpy=1.18.1
  - openblas=0.3.7
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1d
  - pandas=1.1.1
  - pcre=8.43
  - pip=20.0.2
  - pixman=0.38.0
  - psycopg2=2.8.4
  - pthread-stubs=0.4
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - qt=5.9.7
  - readline=7.0
  - scipy=1.4.1
  - setuptools=45.2.0
  - shapely=1.6.4
  - six=1.14.0
  - sqlalchemy=1.3.13
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - absl-py==0.9.0
    - attrs==19.3.0
    - boto3==1.14.41
    - botocore==1.17.41
    - cachetools==4.0.0
    - chardet==3.0.4
    - cloudpickle==1.3.0
    - cycler==0.10.0
    - cython==0.29.24
    - dataclasses==0.8
    - decorator==5.0.9
    - docutils==0.15.2
    - future==0.18.2
    - fvcore==0.1.5.post20210722
    - geographiclib==1.50
    - geopy==1.21.0
    - google-auth==1.11.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.27.1
    - idna==2.8
    - imageio==2.8.0
    - imgaug==0.4.0
    - importlib-metadata==4.6.1
    - iopath==0.1.9
    - jmespath==0.10.0
    - kiwisolver==1.1.0
    - markdown==3.2
    - matplotlib==3.1.3
    - mock==4.0.3
    - more-itertools==8.2.0
    - munkres==1.1.2
    - networkx==2.4
    - oauthlib==3.1.0
    - opencv-python==4.1.2.30
    - openexr==1.3.2
    - packaging==21.0
    - pillow==7.0.0
    - pluggy==0.13.1
    - portalocker==1.5.2
    - protobuf==3.11.3
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydot==1.4.1
    - pyparsing==2.4.6
    - pytest==5.3.5
    - pywavelets==1.1.1
    - pyyaml==5.1
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.7
    - scikit-image==0.17.2
    - tabulate==0.8.9
    - tensorboard==2.1.0
    - termcolor==1.1.0
    - tifffile==2020.9.3
    - tqdm==4.42.1
    - typing-extensions==3.10.0.0
    - urllib3==1.25.8
    - wcwidth==0.2.5
    - werkzeug==1.0.0
    - yacs==0.1.6
    - zipp==3.5.0
